name: Check Xcode Dependencies

on:
  schedule:
    - cron: '0 8 * * 1' # Run weekly on Monday at 8:00 UTC
  workflow_dispatch:

jobs:
  check-dependencies:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 1

      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: latest-stable

      - name: Check for package updates
        id: check-updates
        run: |
          # Store current dependencies
          xcodebuild -resolvePackageDependencies -project PairPods.xcodeproj -json > current_deps.json
          
          # Update dependencies
          xcodebuild -resolvePackageDependencies -project PairPods.xcodeproj -json -disableAutomaticPackageResolution > updated_deps.json

          # Check for differences
          DIFF=$(diff current_deps.json updated_deps.json)
          if [ ! -z "$DIFF" ]; then
            echo "Updates available"
            echo "updates_available=true" >> $GITHUB_OUTPUT
            
            # Extract more readable diff info from the JSON
            echo "# Swift Package Updates Available" > dependency-report.md
            echo "" >> dependency-report.md
            echo "Current packages:" >> dependency-report.md
            echo '```' >> dependency-report.md
            jq -r '.[] | select(.packageKind=="remote") | .name + ": " + .version' current_deps.json >> dependency-report.md 
            echo '```' >> dependency-report.md
            echo "" >> dependency-report.md
            echo "Available updates:" >> dependency-report.md
            echo '```' >> dependency-report.md
            jq -r '.[] | select(.packageKind=="remote") | .name + ": " + .version' updated_deps.json >> dependency-report.md
            echo '```' >> dependency-report.md
          else
            echo "No updates available"
            echo "updates_available=false" >> $GITHUB_OUTPUT
          fi

      - name: Create issue for updates
        if: steps.check-updates.outputs.updates_available == 'true'
        uses: peter-evans/create-issue-from-file@v5.0.1
        with:
          title: Swift Package Dependencies Updates Available
          content-filepath: ./dependency-report.md
          labels: dependencies, maintenance
